server:
  port:  ${PORT:8290}
  
spring:
  application:
    name: ${APP_NAME:cloud-admin-server}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL1:http://localhost:8761/eureka/eureka}
  instance:
    prefer-ip-address: true
