server:
  port: ${PORT:8088}

store:
  url:
    rs-product: ${URL_RS_PRODUCT:}
    
spring:
  application:
    name:  ${APP_NAME:spec-product}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL1:http://localhost:8761/eureka/eureka}
  instance:
    prefer-ip-address: true