server:
  port: ${PORT:8086}

store:
  url:
    rs-user: ${URL_RS_USER:}
    
spring:
  application:
    name:  ${APP_NAME:spec-user}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL1:http://localhost:8761/eureka/eureka}
  instance:
    prefer-ip-address: true